baseURL: "https://fam-lab.github.io/" 
title: FAMLAB
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "This is the official website of the FAM lab, led by Tori Pe単a."
    author: Tori Pe単a, Ph.D.
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","papers","courses","SPARK"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Lecturer of Psychology, Tori Pe単a, Ph.D. (she/her/ella)
          subtitle: "I am a Lecturer in the Department of Psychology at Stony Brook University."
          imageUrl: "picture.jpeg" # to be replaced
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
            - name: SPARK
              url: spark/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character) #to be updated

    socialIcons:
        - name: CV
          url: Pe単a_CV.pdf
        - name: Email
          url: mailto:Tori.Pena@stonybrook.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=gun9xpkAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/pmichaillat #to be updated

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "FAM Lab"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
