baseURL: "https://fam-lab.github.io/" 
title: FAMLAB
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 1 
        - name: Papers
          url: papers/
          weight: 2
        - name: Workshops
          url: workshops/
          weight: 3
        - name: Presentations
          weight: 5

params:
    description: "This is the official website of the FAM lab, led by Tori Pe単a."
    author: Tori Pe単a, Ph.D.
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "October 2025"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","papers","courses","SPARK"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Future and Memory (FaM) Laboratory @ Stony Brook University
          subtitle: "Dr. Tori Pe単a is the director of the FaM lab. Here, we examine the socio-cognitives influences of social remembering and future thinking/imagination. We address a variety of questions such as how does remembering with others change the way we remember the past? How does imagining the future with others shift our emotional valence for our personal and collective future? More recently, we have started examining how engaging with large-language models (LLMs; such as ChatGPT) also shift the way we remember the past and imagine the future."
          imageUrl: "famlablogo.jpeg" # to be replaced
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: Papers
              url: papers/
            - name: Workshops
              url: workshops/
            - name: SPARK
              url: spark/
            - #name: Tags
              #url: tags/
            - name: Presentations
              url: presentations/
            - #name: Blog
              #url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character) #to be updated

    socialIcons:
        - name: CV
          url: Pe単a_CV.pdf
        - name: Email
          url: mailto:Tori.Pena@stonybrook.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=gun9xpkAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/ptori 
          #to be updated

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "FAM Lab"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
